/* -------------------------------------------------------
 * WARNING:
 *
 * This code was generated by the Excel Importer
 * Any changes will be lost, when it gets regenerated.
 * -----------------------------------------------------*/

using System;
using System.Collections.Generic;
using UnityEngine;

namespace Game.Data.Tables
{
    public class PlaceholdersTable : ScriptableObject
    {
        [Serializable]
        public class Row
        {
            public string Key;

        }

        public List<Row> Rows = new List<Row>();
    }
}
